language: node_js
node_js:
  - "6"
branches:
  except:
    - gh-pages
deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    branch: master
cache:
  bundler: true
  directories:
    - node_modules
notifications:
  email: false
